import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>{data?.description?.bodyText}</p>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{}> = async () => {
  const res = await fetch(
    "https://weather.tsukumijima.net/api/forecast/city/400040"
  );
  const data = await res.json();
  return { props: { data } };
};
